project_name: Print2Go

builds:
  - main: ./src/Print2Go.go
    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64
      - mipsle

    gomips:
      - softfloat

dockers:
  - image_templates:
      - ghcr.io/chepo92/print2go:{{ .Version }}

    dockerfile: docker/Dockerfile

    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Print2Go Remote Printer Control
      - --label=org.opencontainers.image.url=https://github.com/chepo92/Print2Go
      - --label=org.opencontainers.image.source=https://github.com/chepo92/Print2Go
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=GPLv3

nfpms:
  - maintainer: Axel Sepulveda
    description: Lightweight remote 3D printer control server.
    homepage: https://github.com/chepo92/Print2Go
    license: GPLv3

    formats:
      - deb
      - rpm
      - apk