#!/bin/sh /etc/rc.common

START=90

USE_PROCD=1


start_service() {
        procd_open_instance
        procd_set_param command /usr/bin/PrintAndGo -tty /dev/ttyUSB0 -listen 192.168.8.155:5001
#        procd_append_param command       
#        procd_set_param respawn  # respawn the service if it exits
#        procd_set_param stdout 1 # forward stdout of the command to logd
#        procd_set_param stderr 1 # same for stderr
        procd_close_instance
}